server:
  port: 8080
spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    #发件人
    username: gaoyuanming_1@163.com
    #授权码
    password: a123456
  datasource:
    url: jdbc:mysql://localhost:3306/health?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc521521521
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

#微信小程序
appId: wx18783a513dd8b26f
appSecret: a45f500599adaeb41de4ee22ace71084